### ISSUE TITLE
老哥用多了无法登录网站了，呜呜呜这个怎么解决呀？（已打赏）

### ISSUE THREAD

**Issue by Abibabodudu** [renzhezhilu/webp2jpg-online-demo#1]
<img width="764" alt="image" src="https://github.com/renzhezhilu/webp2jpg-online-demo/assets/90749771/bc284746-e16c-4d2b-bb11-116d404e02ed">

**Comment by renzhezhilu** [comment]
临时处理： 去掉 连接的 .html  - > https://imagestool.com/zh_CN/compress-images
终究处理：清除浏览器缓存或者换个浏览器
抱歉啊，国庆的时候网站崩了被我一顿操作就出了点小问题

**Comment by Abibabodudu** [comment]
哈哈哈哈哈没事没事能用了！！！谢谢老哥

renzhezhilu ***@***.***>于2023年10月8日 周日11:16写道：
